### ISSUE TITLE
(6) Background 2

### ISSUE THREAD

**Issue by dueruen** [taskhouse/project#30]
Material that you have learned and what we need to know to understand the report, presented from the point of view of your project, but independently of what you have done concretely. (So you might tell us about, e.g., SCRUM, in general terms and perhaps using concrete examples, but not getting into how it has been used in your project.)

- [x] Theory and methods, SCRUM

**Comment by alex6296** [comment]
Drenge en background er ikke teori og methode? det er nok mere Technologi der er det

**Comment by alex6296** [comment]
vil sagtens skrive teori og methoder men det skal nok ikke være her

**Comment by alex6296** [comment]
tak til Victor for at skrive det her i project foundation
